Домашняя работа 4.  Web UI Testing. Selenium Web Driver. Page Object.
Lizzy-29/ElizavetaSayapina_LevelUp pull request #5
Opened 2022-11-14 22:32 UTC by Lizzy-29

2022-11-14 22:49 UTC, Lizzy-29 commented
Комментарий к заданию:

- Не использовала фейкер для генерации почты и пароля, так как  наши тесты проверяют авторизацию, а не регистрацию, согласно условиям домашней работы. Со случайными логином и паролем в почту не зайдешь, так что эти данные захардкожены.

- В силу специфики гугл-почты, которая вся на динамических локаторах приходится много где привязываться к тексту. В связи с этим присутствует много селекторов вида "//*[contains(text(),'Test')]". 
Если у нас в локаторе уже прописано содержимое, мы не можем  проверяемое содержимое рандомно генерировать с помощью фейкера. Потому что в элементе , найденном по локатору //*[contains(text(),'Test')]" просто не будет рандомно сгенерированной абракадабры. Эти данные тоже пришлось захардкодить.

С фейкером обращаться я научилась, но как его применить конкретно в этом тесте - я не нашла.

2022-11-16 06:53 UTC, khda91 requested changes
Исправь пожалуйста комментарии

2022-11-16 06:53 UTC, khda91 commented on src/test/java/ru/levelp/at/homework4/technical_classes/DeleteLetter.java
> +    @FindBy(xpath = "//div//div//div//div//div//div//div//div//div//div[@data-tooltip=\"Выбрать\"]//span")
Нельзя использовать автогенерацию в локаторах

2022-11-16 06:53 UTC, khda91 commented on src/test/java/ru/levelp/at/homework4/technical_classes/DeleteLetter.java
> +    @FindBy(xpath ="//body/div[7]/div[3]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]")
Нельзя использовать автогенерацию в локаторах

2022-11-16 06:53 UTC, khda91 commented on src/test/java/ru/levelp/at/homework4/PageObjectEmailTest.java
> +        var AuthPage = new AuthPage(webDriver);
Имена переменных должны начинаться с маленькой буквы и быть написаны в **camelCase**

2022-11-16 06:53 UTC, khda91 commented on src/test/java/ru/levelp/at/homework4/PageObjectEmailTest.java
> +        var Checks = new Checks(webDriver);
Имена переменных должны начинаться с маленькой буквы и быть написаны в **camelCase**

2022-11-16 06:53 UTC, khda91 commented on src/test/java/ru/levelp/at/homework4/BaseEmailTest.java
> +public class BaseEmailTest {
А этот класс нужен? Я не вижу чтобы оен использовался где-то

2022-11-18 12:13 UTC, closed without merging